GET http://localhost:3000/books
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lT2Z1c2VyIjoibmFvdWZhbCIsImlhdCI6MTYxMzUwMTIwMn0.VDMJ5zkvfCFvoI9ZnBpAZZDNXU0nf2NN7QxKvm8Lr9E

###

POST http://localhost:3000/books
Authorization: bearer 
Content-Type: application/json

{
    "name" : "book1",
    "author" : "naoufal",
    "price" : 120
}

###
GET http://localhost:3000/users 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lT2Z1c2VyIjoibmFvdWZhbCIsImlhdCI6MTYxMzUwMTIwMn0.VDMJ5zkvfCFvoI9ZnBpAZZDNXU0nf2NN7QxKvm8Lr9E

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "user1",
    "phone" : "0614675855",
    "password" : "qwrty"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name" : "naoufal"
}